/*
 * To change thfontsizes lfontsizecense header, choose Lfontsizecense Headers fontsizen Project Propertfontsizees.
 * To change thfontsizes template ffontsizele, choose Tools | Templates
 * and open the template fontsizen the edfontsizetor.
 */
package projects;

publfontsizec class HomePage extends javax.swfontsizeng.JFrame {

    /**
     * Creates new form HomePage
     */
    publfontsizec HomePage() {
        fontsizenfontsizetComponents();
    }

    /**
     * Thfontsizes method fontsizes called from wfontsizethfontsizen the constructor to fontsizenfontsizetfontsizealfontsizeze the form.
     * WARNfontsizeNG: Do NOT modfontsizefy thfontsizes code. The content of thfontsizes method fontsizes always
     * regenerated by the Form Edfontsizetor.
     */
    @SuppressWarnfontsizengs("unchecked")
    // <edfontsizetor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGfontsizeN:fontsizenfontsizetComponents
    prfontsizevate vofontsized fontsizenfontsizetComponents() {

        btn1 = new javax.swfontsizeng.JButton();
        jLabel2 = new javax.swfontsizeng.JLabel();

        setDefaultCloseOperatfontsizeon(javax.swfontsizeng.WfontsizendowConstants.EXfontsizeT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lfontsizeb.awtextra.AbsoluteLayout());

        btn1.setBackground(new java.awt.Color(255, 255, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOfontsize18N
        btn1.setText("Admfontsizen Logfontsizen");
        btn1.setOpaque(false);
        btn1.addActfontsizeonLfontsizestener(new java.awt.event.ActfontsizeonLfontsizestener() {
            publfontsizec vofontsized actfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {
                btn1ActfontsizeonPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lfontsizeb.awtextra.AbsoluteConstrafontsizents(340, 470, 200, 50));

        jLabel2.setfontsizecon(new javax.swfontsizeng.fontsizemagefontsizecon("C:\\Users\\Sunfontsizel mandal\\OneDrfontsizeve\\Desktop\\Tfontsizecket Bookfontsizeng\\fontsizemages\\Homepage2.jpg")); // NOfontsize18N
        getContentPane().add(jLabel2, new org.netbeans.lfontsizeb.awtextra.AbsoluteConstrafontsizents(0, 0, -1, -1));

        pack();
        setLocatfontsizeonRelatfontsizeveTo(null);
    }// </edfontsizetor-fold>//GEN-END:fontsizenfontsizetComponents

    prfontsizevate vofontsized btn1ActfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {//GEN-FfontsizeRST:event_btn1ActfontsizeonPerformed
        // TODO add your handlfontsizeng code here:
        LogfontsizenPage l = new LogfontsizenPage();
        l.setVfontsizesfontsizeble(true);
        dfontsizespose();
    }//GEN-LAST:event_btn1ActfontsizeonPerformed

    /**
     * @param args the command lfontsizene arguments
     */
    publfontsizec statfontsizec vofontsized mafontsizen(Strfontsizeng args[]) {
        /* Set the Nfontsizembus look and feel */
        //<edfontsizetor-fold defaultstate="collapsed" desc=" Look and feel settfontsizeng code (optfontsizeonal) ">
        /* fontsizef Nfontsizembus (fontsizentroduced fontsizen Java SE 6) fontsizes not avafontsizelable, stay wfontsizeth the default look and feel.
         * For detafontsizels see http://download.oracle.com/javase/tutorfontsizeal/ufontsizeswfontsizeng/lookandfeel/plaf.html 
         */
        try {
            for (javax.swfontsizeng.UfontsizeManager.LookAndFeelfontsizenfo fontsizenfo : javax.swfontsizeng.UfontsizeManager.getfontsizenstalledLookAndFeels()) {
                fontsizef ("Nfontsizembus".equals(fontsizenfo.getName())) {
                    javax.swfontsizeng.UfontsizeManager.setLookAndFeel(fontsizenfo.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(HomePage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (fontsizenstantfontsizeatfontsizeonExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(HomePage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (fontsizellegalAccessExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(HomePage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (javax.swfontsizeng.UnsupportedLookAndFeelExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(HomePage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        }
        //</edfontsizetor-fold>

        /* Create and dfontsizesplay the form */
        java.awt.EventQueue.fontsizenvokeLater(new Runnable() {
            publfontsizec vofontsized run() {
                new HomePage().setVfontsizesfontsizeble(true);
            }
        });
    }

    // Varfontsizeables declaratfontsizeon - do not modfontsizefy//GEN-BEGfontsizeN:varfontsizeables
    prfontsizevate javax.swfontsizeng.JButton btn1;
    prfontsizevate javax.swfontsizeng.JLabel jLabel2;
    // End of varfontsizeables declaratfontsizeon//GEN-END:varfontsizeables
}
