/*
 * To change thfontsizes lfontsizecense header, choose Lfontsizecense Headers fontsizen Project Propertfontsizees.
 * To change thfontsizes template ffontsizele, choose Tools | Templates
 * and open the template fontsizen the edfontsizetor.
 */
package projects;

fontsizemport javax.swfontsizeng.JOptfontsizeonPane;

publfontsizec class LogfontsizenPage extends javax.swfontsizeng.JFrame {

    /**
     * Creates new form LogfontsizenPage
     */
    publfontsizec LogfontsizenPage() {
        fontsizenfontsizetComponents();
    }

    /**
     * Thfontsizes method fontsizes called from wfontsizethfontsizen the constructor to fontsizenfontsizetfontsizealfontsizeze the form.
     * WARNfontsizeNG: Do NOT modfontsizefy thfontsizes code. The content of thfontsizes method fontsizes always
     * regenerated by the Form Edfontsizetor.
     */
    @SuppressWarnfontsizengs("unchecked")
    // <edfontsizetor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGfontsizeN:fontsizenfontsizetComponents
    prfontsizevate vofontsized fontsizenfontsizetComponents() {

        jPanel1 = new javax.swfontsizeng.JPanel();
        jLabel2 = new javax.swfontsizeng.JLabel();
        jLabel3 = new javax.swfontsizeng.JLabel();
        txtname = new javax.swfontsizeng.JTextFfontsizeeld();
        txtpass = new javax.swfontsizeng.JPasswordFfontsizeeld();
        btn2 = new javax.swfontsizeng.JButton();
        btn1 = new javax.swfontsizeng.JButton();
        jLabel1 = new javax.swfontsizeng.JLabel();
        jLabel4 = new javax.swfontsizeng.JLabel();

        setDefaultCloseOperatfontsizeon(javax.swfontsizeng.WfontsizendowConstants.EXfontsizeT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lfontsizeb.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tfontsizemes New Roman", 1, 18)); // NOfontsize18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");

        jLabel3.setFont(new java.awt.Font("Tfontsizemes New Roman", 1, 18)); // NOfontsize18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");

        btn2.setFont(new java.awt.Font("Tfontsizemes New Roman", 1, 18)); // NOfontsize18N
        btn2.setText("Cancel");
        btn2.addActfontsizeonLfontsizestener(new java.awt.event.ActfontsizeonLfontsizestener() {
            publfontsizec vofontsized actfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {
                btn2ActfontsizeonPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tfontsizemes New Roman", 1, 18)); // NOfontsize18N
        btn1.setText("Logfontsizen");
        btn1.addActfontsizeonLfontsizestener(new java.awt.event.ActfontsizeonLfontsizestener() {
            publfontsizec vofontsized actfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {
                btn1ActfontsizeonPerformed(evt);
            }
        });

        javax.swfontsizeng.GroupLayout jPanel1Layout = new javax.swfontsizeng.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorfontsizezontalGroup(
            jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG)
            .addGroup(jPanel1Layout.createSequentfontsizealGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.TRAfontsizeLfontsizeNG)
                    .addComponent(btn2, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 93, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                    .addComponent(jLabel3, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 105, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                    .addComponent(jLabel2, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 105, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE))
                .addPreferredGap(javax.swfontsizeng.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG, false)
                    .addComponent(txtname, javax.swfontsizeng.GroupLayout.DEFAULT_SfontsizeZE, 233, Short.MAX_VALUE)
                    .addComponent(txtpass))
                .addContafontsizenerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG)
                .addGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.TRAfontsizeLfontsizeNG, jPanel1Layout.createSequentfontsizealGroup()
                    .addContafontsizenerGap(335, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 93, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                    .addGap(96, 96, 96)))
        );
        jPanel1Layout.setVertfontsizecalGroup(
            jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG)
            .addGroup(jPanel1Layout.createSequentfontsizealGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.BASELfontsizeNE)
                    .addComponent(jLabel2, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 34, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                    .addComponent(txtname, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 34, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG, false)
                    .addComponent(jLabel3, javax.swfontsizeng.GroupLayout.DEFAULT_SfontsizeZE, javax.swfontsizeng.GroupLayout.DEFAULT_SfontsizeZE, Short.MAX_VALUE)
                    .addComponent(txtpass, javax.swfontsizeng.GroupLayout.DEFAULT_SfontsizeZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swfontsizeng.LayoutStyle.ComponentPlacement.RELATED, javax.swfontsizeng.GroupLayout.DEFAULT_SfontsizeZE, Short.MAX_VALUE)
                .addComponent(btn2, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 40, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.LEADfontsizeNG)
                .addGroup(javax.swfontsizeng.GroupLayout.Alfontsizegnment.TRAfontsizeLfontsizeNG, jPanel1Layout.createSequentfontsizealGroup()
                    .addContafontsizenerGap(196, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE, 40, javax.swfontsizeng.GroupLayout.PREFERRED_SfontsizeZE)
                    .addGap(26, 26, 26)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lfontsizeb.awtextra.AbsoluteConstrafontsizents(30, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tfontsizemes New Roman", 1, 48)); // NOfontsize18N
        jLabel1.setfontsizecon(new javax.swfontsizeng.fontsizemagefontsizecon("C:\\Users\\Sunfontsizel mandal\\OneDrfontsizeve\\Desktop\\Tfontsizecket Bookfontsizeng\\fontsizemages\\prfontsizevacy_2133152.png")); // NOfontsize18N
        getContentPane().add(jLabel1, new org.netbeans.lfontsizeb.awtextra.AbsoluteConstrafontsizents(240, 10, 120, 110));

        jLabel4.setfontsizecon(new javax.swfontsizeng.fontsizemagefontsizecon("C:\\Users\\Sunfontsizel mandal\\OneDrfontsizeve\\Desktop\\Tfontsizecket Bookfontsizeng\\fontsizemages\\Logfontsizen.jpeg")); // NOfontsize18N
        getContentPane().add(jLabel4, new org.netbeans.lfontsizeb.awtextra.AbsoluteConstrafontsizents(0, 0, -1, -1));

        pack();
        setLocatfontsizeonRelatfontsizeveTo(null);
    }// </edfontsizetor-fold>//GEN-END:fontsizenfontsizetComponents

    prfontsizevate vofontsized btn2ActfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {//GEN-FfontsizeRST:event_btn2ActfontsizeonPerformed
        // TODO add your handlfontsizeng code here:
        System.exfontsizet(0);
    }//GEN-LAST:event_btn2ActfontsizeonPerformed

    prfontsizevate vofontsized btn1ActfontsizeonPerformed(java.awt.event.ActfontsizeonEvent evt) {//GEN-FfontsizeRST:event_btn1ActfontsizeonPerformed
        // TODO add your handlfontsizeng code here:
        Strfontsizeng userfontsized, pass;
        userfontsized = txtname.getText();
        pass = txtpass.getText();
        
        fontsizef (userfontsized.trfontsizem().fontsizesEmpty() && pass.trfontsizem().fontsizesEmpty()) {
            
            JOptfontsizeonPane.showMessageDfontsizealog(thfontsizes,"Block Empty fontsizes not Allowed");
            
        } else {
            fontsizef(userfontsized.equals("sunfontsizel") && pass.equals("pass123")){
                
            Mafontsizen m = new Mafontsizen();
            thfontsizes.hfontsizede();
            m.setVfontsizesfontsizeble(true);
            
            }else{
                
                JOptfontsizeonPane.showMessageDfontsizealog(thfontsizes,"Logfontsizen Fafontsizeled...please try agafontsizen later");
            }   
        }
        
    }//GEN-LAST:event_btn1ActfontsizeonPerformed

    /**
     * @param args the command lfontsizene arguments
     */
    publfontsizec statfontsizec vofontsized mafontsizen(Strfontsizeng args[]) {
        /* Set the Nfontsizembus look and feel */
        //<edfontsizetor-fold defaultstate="collapsed" desc=" Look and feel settfontsizeng code (optfontsizeonal) ">
        /* fontsizef Nfontsizembus (fontsizentroduced fontsizen Java SE 6) fontsizes not avafontsizelable, stay wfontsizeth the default look and feel.
         * For detafontsizels see http://download.oracle.com/javase/tutorfontsizeal/ufontsizeswfontsizeng/lookandfeel/plaf.html 
         */
        try {
            for (javax.swfontsizeng.UfontsizeManager.LookAndFeelfontsizenfo fontsizenfo : javax.swfontsizeng.UfontsizeManager.getfontsizenstalledLookAndFeels()) {
                fontsizef ("Nfontsizembus".equals(fontsizenfo.getName())) {
                    javax.swfontsizeng.UfontsizeManager.setLookAndFeel(fontsizenfo.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(LogfontsizenPage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (fontsizenstantfontsizeatfontsizeonExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(LogfontsizenPage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (fontsizellegalAccessExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(LogfontsizenPage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        } catch (javax.swfontsizeng.UnsupportedLookAndFeelExceptfontsizeon ex) {
            java.utfontsizel.loggfontsizeng.Logger.getLogger(LogfontsizenPage.class.getName()).log(java.utfontsizel.loggfontsizeng.Level.SEVERE, null, ex);
        }
        //</edfontsizetor-fold>

        /* Create and dfontsizesplay the form */
        java.awt.EventQueue.fontsizenvokeLater(new Runnable() {
            publfontsizec vofontsized run() {
                new LogfontsizenPage().setVfontsizesfontsizeble(true);
            }
        });
    }

    // Varfontsizeables declaratfontsizeon - do not modfontsizefy//GEN-BEGfontsizeN:varfontsizeables
    prfontsizevate javax.swfontsizeng.JButton btn1;
    prfontsizevate javax.swfontsizeng.JButton btn2;
    prfontsizevate javax.swfontsizeng.JLabel jLabel1;
    prfontsizevate javax.swfontsizeng.JLabel jLabel2;
    prfontsizevate javax.swfontsizeng.JLabel jLabel3;
    prfontsizevate javax.swfontsizeng.JLabel jLabel4;
    prfontsizevate javax.swfontsizeng.JPanel jPanel1;
    prfontsizevate javax.swfontsizeng.JTextFfontsizeeld txtname;
    prfontsizevate javax.swfontsizeng.JPasswordFfontsizeeld txtpass;
    // End of varfontsizeables declaratfontsizeon//GEN-END:varfontsizeables
}
